sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t siddharthrajkumar/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true siddharthrajkumar/react-test npm run test

after_success:
  - docker build -t siddharthrajkumar/multi-client ./client
  - docker build -t siddharthrajkumar/multi-nginx ./nginx
  - docker build -t siddharthrajkumar/multi-server ./server
  - docker build -t siddharthrajkumar/multi-worker ./worker
