FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf

# removed from default.conf for production
# location /ws {
#         proxy_pass http://client;
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection "Upgrade";
#     }